baseURL = 'http://rafasacaan.github.io/pots-and-pans/'
languageCode = 'en-us'
title = 'pots and pans.'
theme ="PaperMod"

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = true
buildFuture = false
buildExpired = false
enableEmoji = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
ShowShareButtons = false
ShowReadingTime = true
displayFullLangName = false
ShowPostNavLinks = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = false

[params.homeInfoParams]
Title = "🍯 & 🍳 "
Content = "[BETA] Welcome! this is an attempt to write short code reminders that I usually forget. It´s all in the pots and pans."
